import Head from "next/head";
import { ImgHTMLAttributes, useState } from "react";
import Carousel from "react-multi-carousel";
import NavigationBar from "./components/NavigationBar";
import Link from "next/link";

import "react-multi-carousel/lib/styles.css";
import { Poppins, Yellowtail } from "next/font/google";
import Container from "./components/Container";
import { FaMapMarkerAlt } from "react-icons/fa";
import { IoTicketOutline } from "react-icons/io5";
import { AiFillStar } from "react-icons/ai";
import { Divider } from "react-daisyui";
import SideCard from "./components/SideCard";

const yellowTail = Yellowtail({
    weight: "400",
    subsets: ["latin"]
});
const poppins = Poppins({
    weight: "400",
    subsets: ["latin"]
});

const Plan = () => {
    const [image, setImage] = useState([
        "https://picsum.photos/seed/picsum/1336/379",
        "https://images.unsplash.com/photo-1550133730-695473e544be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        "https://images.unsplash.com/photo-1550133730-695473e544be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        "https://images.unsplash.com/photo-1550133730-695473e544be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        "https://images.unsplash.com/photo-1550133730-695473e544be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60",
        "https://images.unsplash.com/photo-1550133730-695473e544be?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60"
    ]);
    const [currentImage, setCurrentImage] = useState(image[0]);

    const handlerClickImg = (e: React.MouseEvent) => {
        const target = e.target as HTMLImageElement;
        setCurrentImage(target.src);
    };
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavigationBar>
                <section className="pt-10">
                    <div className="flex flex-col items-center gap-7 ">
                        <div className="h-[379px] w-[1336px]">
                            <img src={currentImage} className="h-full w-full" />
                        </div>
                        <Carousel
                            additionalTransfrom={0}
                            arrows
                            autoPlaySpeed={3000}
                            centerMode={false}
                            className="h-[104px] w-[900px] "
                            containerClass="container"
                            dotListClass=""
                            draggable
                            focusOnSelect={false}
                            itemClass=""
                            keyBoardControl
                            minimumTouchDrag={80}
                            pauseOnHover
                            renderArrowsWhenDisabled={false}
                            renderButtonGroupOutside={false}
                            renderDotsOutside={false}
                            responsive={{
                                desktop: {
                                    breakpoint: {
                                        max: 3000,
                                        min: 1024
                                    },
                                    items: 4,
                                    partialVisibilityGutter: 40
                                },
                                mobile: {
                                    breakpoint: {
                                        max: 464,
                                        min: 0
                                    },
                                    items: 1,
                                    partialVisibilityGutter: 30
                                },
                                tablet: {
                                    breakpoint: {
                                        max: 1024,
                                        min: 464
                                    },
                                    items: 2,
                                    partialVisibilityGutter: 30
                                }
                            }}
                            rewind={false}
                            rewindWithAnimation={false}
                            rtl={false}
                            shouldResetAutoplay
                            sliderClass=""
                            slidesToSlide={1}
                            swipeable
                        >
                            {image.map((v, i) => (
                                <div key={i} className="mx-5 h-full">
                                    <img
                                        src={v}
                                        onClick={handlerClickImg}
                                        className="h-full w-full"
                                    />
                                </div>
                            ))}
                        </Carousel>
                    </div>
                </section>
                <Container className="mt-20 px-20">
                    <section className={`${poppins.className}`}>
                        <span className={` text-[40px] font-bold`}>
                            Labuan bajo adventure trip
                        </span>
                        <div className="flex leading-none">
                            <span className="flex items-center gap-1 text-[15px]">
                                <FaMapMarkerAlt /> Nusa tenggara timur
                            </span>
                            <Divider vertical>|</Divider>
                            <span className="flex items-center gap-1 text-[15px]">
                                <AiFillStar />
                                <span className="text-[15px] font-semibold">
                                    4.1
                                </span>
                                <Link href={"#"} className="underline">
                                    6.7RB Review
                                </Link>
                            </span>
                            <Divider vertical>|</Divider>
                            <span className="flex items-center gap-1 text-[15px]">
                                <IoTicketOutline className="origin-center  rotate-45" />
                                <span className="text-[15px] font-semibold">
                                    200RB
                                </span>
                                Terjual
                            </span>
                        </div>

                        <p className="text-[15px] leading-none text-[#1DA1F2] underline">
                            <Link href={"#"}>See on Map</Link>
                        </p>
                    </section>
                </Container>
                <SideCard>
                    <Container className="absolute -mt-[667px] w-[70%]  px-20">
                        <section className={`${poppins.className}  `}>
                            <p className="mt-5 text-[18px]">
                                Lorem ipsum dolor sit amet, consectetur
                                adipiscing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua. Ut
                                enim ad minim veniam, quis nostrud exercitation
                                ullamco laboris nisi ut aliquip ex ea commodo
                                consequat.
                            </p>

                            <p className="mt-4 text-[20px] font-semibold text-[#1DA1F2]   underline ">
                                <Link href={"#"}>Read more</Link>
                            </p>
                        </section>
                        <Divider></Divider>
                        <section className={`${poppins.className}`}>
                            <span className="text-[24px] font-semibold">
                                About this plan
                            </span>

                            <div className="mt-10 flex w-full justify-between">
                                <div className="w-full">
                                    <p className="text-center text-[20px]">
                                        Online Plan
                                    </p>
                                    <div></div>
                                </div>
                                <div className="divider divider-horizontal"></div>
                                <div className="w-full">
                                    <p className="text-center text-[20px]">
                                        Offline Plan
                                    </p>
                                </div>
                            </div>
                        </section>
                    </Container>
                </SideCard>
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
                <br />
            </NavigationBar>
        </>
    );
};

export default Plan;
